# Generated by Django 3.2.7 on 2021-11-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feasoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_flag', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'FEASOC',
                'db_table': 'r_feasoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobhdr',
            fields=[
                ('job_num', models.IntegerField(blank=True, db_column='JOB_NUM', null=True, primary_key=True, serialize=False)),
                ('fe_id', models.IntegerField(blank=True, null=True)),
                ('f_id', models.IntegerField(blank=True, db_column='F_ID', null=True)),
                ('job_status', models.CharField(blank=True, max_length=6, null=True)),
                ('work_type', models.CharField(blank=True, max_length=6, null=True)),
                ('pri_code', models.CharField(blank=True, max_length=6, null=True)),
                ('target_end_date', models.DateTimeField(blank=True, null=True)),
                ('next_step', models.CharField(blank=True, max_length=6, null=True)),
                ('ser_code', models.IntegerField(blank=True, null=True)),
                ('rqtr', models.CharField(blank=True, db_column='RQTR', max_length=6, null=True)),
                ('rqt_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('plan_start_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'JOBHDR Jobs',
                'db_table': 'R_JOBHDR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobtas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_num', models.IntegerField(blank=True, null=True)),
                ('task_status', models.CharField(blank=True, max_length=6, null=True)),
                ('task_title', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('plan_start_date', models.DateTimeField(blank=True, null=True)),
                ('target_end_date', models.DateTimeField(blank=True, null=True)),
                ('work_order_id', models.IntegerField(blank=True, null=True)),
                ('fin_unit_code', models.CharField(blank=True, max_length=6, null=True)),
                ('assurance_task', models.CharField(blank=True, max_length=6, null=True)),
                ('prod_crit_eqpt', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'JOBTAS Jobs',
                'db_table': 'r_jobtas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orgtbl',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', null=True, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Organization Code',
                'db_table': 'r_orgtbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users Table',
                'db_table': 'r_userrg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('orgn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('dept', models.CharField(blank=True, choices=[('PCM', 'PCM'), ('PCN-B', 'PCN-B'), ('PCN-C', 'PCN-C'), ('PGM', 'PGM'), ('PIC', 'PIC'), ('PII', 'PII'), ('PIQ', 'PIQ'), ('PIR', 'PIR'), ('PMF', 'PMF'), ('PMI', 'PMI'), ('PMS', 'PMS'), ('PMN', 'PMN'), ('PMT', 'PMT'), ('PMW', 'PMW'), ('PTM-D', 'PTM-D'), ('PTM-E', 'PTM-E'), ('TPP', 'TPP'), ('HSE', 'HSE')], max_length=10, null=True, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Femast',
            fields=[
                ('id', models.ForeignKey(blank=True, db_column='ID', null=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backlog.jobhdr')),
                ('fe_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fe_key', models.CharField(blank=True, max_length=50, null=True)),
                ('fe_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('vet_flag', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'FEMAST',
                'db_table': 'r_femast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobhdtas',
            fields=[
                ('id', models.IntegerField(blank=True, null=True, primary_key=True, serialize=False)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backlog.dept')),
                ('jobhdr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backlog.jobhdr')),
                ('jobtas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backlog.jobtas')),
                ('orgtbl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backlog.orgtbl')),
                ('userrg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backlog.userrg')),
                ('femast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backlog.femast')),
            ],
        ),
    ]
