# Generated by Django 3.2.7 on 2021-11-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhdtas',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='jobhdtas',
            name='femast',
        ),
        migrations.RemoveField(
            model_name='jobhdtas',
            name='jobhdr',
        ),
        migrations.RemoveField(
            model_name='jobhdtas',
            name='jobtas',
        ),
        migrations.RemoveField(
            model_name='jobhdtas',
            name='orgtbl',
        ),
        migrations.RemoveField(
            model_name='jobhdtas',
            name='userrg',
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.DeleteModel(
            name='Jobhdtas',
        ),
    ]
