# Generated by Django 3.2.7 on 2021-11-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_auto_20211109_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estmis',
            fields=[
                ('rqt_no', models.ForeignKey(blank=True, db_column='RQT_NO', null=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backlog.jobhdr')),
                ('unit_rate', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('task_num', models.IntegerField(blank=True, null=True)),
                ('ref_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estmis',
                'db_table': 'R_ESTMIS',
                'managed': False,
            },
        ),
    ]
